export enum OrdemStatus {
  RECEBIDA = "RECEBIDA",
  DIAGNOSTICO = "DIAGNOSTICO",
  AGUARDANDO_APROVACAO = "AGUARDANDO_APROVACAO",
  EXECUCAO = "EXECUCAO",
  FINALIZADA = "FINALIZADA",
  ENTREGUE = "ENTREGUE"
}