apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oficina-api
  template:
    metadata:
      labels:
        app: oficina-api
    spec:
      containers:
        - name: api
          image: oficina-api:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: oficina-secret
            - configMapRef:
                name: oficina-config