apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oficina-api
  template:
    metadata:
      labels:
        app: oficina-api
    spec:
      containers:
        - name: api
          image: xungrelo/oficina-api:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: oficina-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oficina-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: oficina-api-service
spec:
  selector:
    app: oficina-api
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000