apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oficina-api
  template:
    metadata:
      labels:
        app: oficina-api
    spec:
      containers:
        - name: api
          image: oficina-api:latest
          ports:
            - containerPort: 3000

          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"

          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@db:5432/oficina
            - name: JWT_SECRET
              value: supersecret